### ISSUE TITLE
Missing files

### ISSUE THREAD

**Issue by ghost** [DankPaster/MutinyFixed#1]
Could you include ClientFramework and Framework
![image](https://user-images.githubusercontent.com/28850156/34806984-1a27779a-f654-11e7-8906-d7ef259f970b.png)

**Comment by xKaizo** [comment]
Just get the ClientFramework from here and place it in your `C:\` drive
http://www.mediafire.com/file/avtqfpb4lnopeun/ClientFramework.zip

**Comment by DankPaster** [comment]
Download ClientFramework @xKaizo posted and put it on your C drive.
